name: Keep Backend Alive

on:
  schedule:
    - cron: '*/13 8-18 * * 1-5'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl https://byte-spot-rest-api.onrender.com/api/locations